---

- hosts: all
  become: true
  tasks:
      
   - name: update repository index (CentOS)
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "CentOS"

   - name: update repository index (Ubuntu)
     apt:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  
   - name: install apache2 and php packages  for debian based distribution
     apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
     when: ansible_distribution == ["Ubuntu", "Debian"]
        
   - name: install apache and php packages for CentOS
     dnf:
        name: 
          - httpd
          - php
        state: latest
        update_cache: yes
     when: ansible_distribution == "CentOS"